type T3 = { fr: string; en: string; ar: string }
export type GuideSeed = {
  slug: string
  theme: 'installation' | 'demarches' | 'quotidien' | 'decouvrir' | 'business'
  title: T3
  summary: T3
  steps: string[]
  /** true : contenu repris du prototype validé → publié. false : rédigé par Claude → brouillon à valider. */
  approved: boolean
}
const t = (fr: string, en: string, ar: string): T3 => ({ fr, en, ar })

export const GUIDES: GuideSeed[] = [
  {
    slug: 'preparer-son-installation',
    theme: 'installation',
    approved: true,
    title: t('Préparer son installation', 'Preparing your move', 'التحضير للاستقرار'),
    summary: t('Clarifier son projet, organiser son départ et préparer ses premiers mois.', 'Clarify your project, organise your departure and prepare your first months.', 'توضيح مشروعك، تنظيم رحيلك وتحضير أشهرك الأولى.'),
    steps: [
      'Notez ce qui motive votre installation, votre horizon et les contraintes de votre foyer.',
      'Repérez les documents dont vous disposez et les démarches à confirmer selon votre nationalité et votre situation.',
      'Comparez plusieurs villes en fonction de votre quotidien : logement, école, soins, travail et déplacements.',
      'Prévoyez un séjour de repérage si possible, puis organisez un budget et une solution de logement à l’arrivée.',
      'Préparez vos premières semaines : contacts utiles, rendez-vous, scolarité et continuité des soins.',
    ],
  },
  {
    slug: 'choisir-sa-ville',
    theme: 'installation',
    approved: false,
    title: t('Choisir sa ville et son quartier', 'Choosing your city and neighbourhood', 'اختيار المدينة والحي'),
    summary: t('Comparer un cadre de vie concret, au-delà des photos et des impressions.', 'Compare real living conditions, beyond photos and impressions.', 'مقارنة إطار حياة ملموس، أبعد من الصور والانطباعات.'),
    steps: [
      'Listez vos besoins quotidiens : travail, écoles, soins, commerces, lieux de prière, transports.',
      'Comparez deux ou trois quartiers sur les mêmes critères, aux heures où vous les utiliserez.',
      'Renseignez-vous sur l’accès à l’eau, l’électricité, internet et le stationnement.',
      'Échangez avec des habitants et croisez leurs retours avec des informations vérifiables.',
      'Gardez une solution temporaire le temps de confirmer votre choix sur place.',
    ],
  },
  {
    slug: 'documents-et-demarches',
    theme: 'demarches',
    approved: true,
    title: t('Documents et démarches', 'Documents and procedures', 'الوثائق والإجراءات'),
    summary: t('Identifier les bons interlocuteurs et préparer un dossier adapté à sa situation.', 'Identify the right offices and prepare a file suited to your situation.', 'تحديد المحاورين المناسبين وتحضير ملف يناسب وضعك.'),
    steps: [
      'Identifiez les démarches qui dépendent de votre nationalité, de votre résidence et de votre situation familiale.',
      'Consultez la liste actuelle des pièces sur le site de l’autorité compétente avant de préparer le dossier.',
      'Vérifiez les règles concernant originaux, copies, traductions, rendez-vous et dates de validité.',
      'Pour votre déménagement, interrogez les douanes avant tout achat ou expédition.',
      'Conservez les références des demandes et les confirmations reçues.',
    ],
  },
  {
    slug: 'logement',
    theme: 'installation',
    approved: true,
    title: t('Préparer sa recherche de logement', 'Preparing your housing search', 'التحضير للبحث عن سكن'),
    summary: t('Définir ses critères, préparer les visites et vérifier les conditions avant de s’engager.', 'Define your criteria, prepare visits and check the terms before committing.', 'تحديد معاييرك، تحضير الزيارات والتحقق من الشروط قبل الالتزام.'),
    steps: [
      'Définissez le quartier, la surface, les déplacements et votre budget total.',
      'Préparez une liste de points à examiner : état du logement, eau, électricité, internet et environnement.',
      'Faites préciser par écrit le prix, les charges, la durée et les modalités de paiement.',
      'Vérifiez l’identité et la qualité du signataire avec un interlocuteur compétent avant tout engagement.',
      'Gardez une copie des documents et un état des lieux détaillé.',
    ],
  },
  {
    slug: 'ecole-et-famille',
    theme: 'quotidien',
    approved: true,
    title: t('École et vie de famille', 'School and family life', 'المدرسة والحياة العائلية'),
    summary: t('Préparer la scolarité et les repères du quotidien pour les enfants.', 'Prepare schooling and everyday landmarks for children.', 'تحضير التمدرس ومعالم الحياة اليومية للأطفال.'),
    steps: [
      'Identifiez les établissements adaptés à l’âge et au parcours scolaire de vos enfants.',
      'Demandez directement les conditions d’inscription, le calendrier et les pièces nécessaires.',
      'Renseignez-vous sur les langues, les programmes et l’accompagnement proposé.',
      'Évaluez les trajets, les horaires et l’organisation familiale.',
      'Prévoyez une période d’adaptation et gardez un lien avec l’équipe éducative.',
    ],
  },
  {
    slug: 'sante',
    theme: 'quotidien',
    approved: true,
    title: t('Préparer son accès aux soins', 'Preparing your access to healthcare', 'التحضير للحصول على العلاج'),
    summary: t('Organiser la continuité des soins et repérer les interlocuteurs utiles.', 'Organise continuity of care and find the right contacts.', 'تنظيم استمرارية العلاج وتحديد المحاورين المفيدين.'),
    steps: [
      'Préparez avec vos soignants les éléments utiles à la continuité de votre suivi.',
      'Identifiez les structures et professionnels adaptés à vos besoins près du futur logement.',
      'Vérifiez votre couverture et les démarches auprès de l’organisme concerné.',
      'Si vous suivez un traitement, préparez sa continuité avec votre médecin et votre pharmacien.',
      'Conservez les coordonnées utiles et les documents médicaux dans un espace privé.',
    ],
  },
  {
    slug: 'budget-et-banque',
    theme: 'demarches',
    approved: false,
    title: t('Budget et démarches bancaires', 'Budget and banking', 'الميزانية والإجراءات البنكية'),
    summary: t('Estimer son budget et préparer l’ouverture d’un compte.', 'Estimate your budget and prepare to open an account.', 'تقدير ميزانيتك والتحضير لفتح حساب.'),
    steps: [
      'Estimez vos dépenses mensuelles : logement, alimentation, transport, scolarité, santé.',
      'Renseignez-vous auprès de plusieurs banques sur les comptes accessibles à votre situation.',
      'Demandez la liste des pièces à fournir et les délais d’ouverture.',
      'Vérifiez les règles applicables aux transferts et au change auprès des organismes officiels.',
      'Gardez une réserve pour les premières semaines, le temps que tout soit en place.',
    ],
  },
  {
    slug: 'travail-et-entreprise',
    theme: 'business',
    approved: true,
    title: t('Travailler et entreprendre', 'Working and starting a business', 'العمل وإنشاء مؤسسة'),
    summary: t('Préparer son activité et identifier les démarches auprès des organismes compétents.', 'Prepare your activity and identify procedures with the relevant bodies.', 'تحضير نشاطك وتحديد الإجراءات لدى الهيئات المختصة.'),
    steps: [
      'Clarifiez votre projet : emploi salarié, activité indépendante ou création d’entreprise.',
      'Identifiez les qualifications, autorisations ou inscriptions à vérifier pour votre métier.',
      'Consultez les organismes officiels pour les démarches correspondant à votre statut.',
      'Préparez une étude de vos clients, charges et besoins de financement.',
      'Faites confirmer les obligations fiscales et sociales par un professionnel compétent.',
    ],
  },
  {
    slug: 'transport',
    theme: 'quotidien',
    approved: true,
    title: t('Se déplacer au quotidien', 'Getting around', 'التنقل اليومي'),
    summary: t('Repérer les trajets, les réseaux et les conditions de transport avant l’arrivée.', 'Map out routes, networks and transport conditions before you arrive.', 'التعرّف على المسارات والشبكات وشروط النقل قبل الوصول.'),
    steps: [
      'Repérez vos trajets les plus fréquents entre logement, travail et établissements scolaires.',
      'Consultez les horaires et tarifs directement auprès des opérateurs.',
      'Testez les trajets quand cela est possible, en tenant compte des heures d’affluence.',
      'Si vous conduisez, vérifiez les formalités concernant permis, véhicule et assurance.',
      'Prévoyez une solution de remplacement pour les déplacements essentiels.',
    ],
  },
  {
    slug: 'internet-et-telecoms',
    theme: 'quotidien',
    approved: false,
    title: t('Internet et télécommunications', 'Internet and phone', 'الإنترنت والاتصالات'),
    summary: t('Choisir une ligne mobile et une connexion adaptées à son usage.', 'Choose a mobile line and connection that fit your use.', 'اختيار خط هاتفي واتصال يناسبان استعمالك.'),
    steps: [
      'Définissez votre usage : appels, données mobiles, télétravail, visioconférence.',
      'Comparez les offres des opérateurs directement sur leurs canaux officiels.',
      'Vérifiez la couverture et l’éligibilité de votre adresse avant de vous engager.',
      'Préparez les pièces demandées pour l’abonnement.',
      'Gardez une solution de secours (partage de connexion, seconde ligne) pour le travail.',
    ],
  },
  {
    slug: 'decouvrir-algerie',
    theme: 'decouvrir',
    approved: true,
    title: t('Découvrir les régions et la vie locale', 'Discovering regions and local life', 'اكتشاف المناطق والحياة المحلية'),
    summary: t('Préparer ses découvertes, ses sorties et ses repères culturels.', 'Plan your discoveries, outings and cultural landmarks.', 'تحضير اكتشافاتك وخرجاتك ومعالمك الثقافية.'),
    steps: [
      'Choisissez une région et renseignez-vous sur ses lieux, ses saisons et ses possibilités de déplacement.',
      'Vérifiez les horaires, conditions d’accès et disponibilités auprès des lieux concernés.',
      'Croisez les témoignages avec les informations des organisateurs et institutions locales.',
      'Respectez les consignes propres aux lieux visités et aux espaces naturels.',
      'Gardez vos découvertes et proposez une information au guide si elle peut être utile aux autres.',
    ],
  },
  {
    slug: 'sorties-en-famille',
    theme: 'decouvrir',
    approved: true,
    title: t('Sorties, loisirs et découvertes', 'Outings, leisure and discoveries', 'خرجات وترفيه واكتشافات'),
    summary: t('Parcs, jardins, musées, plages et activités : préparer une sortie qui convient à chacun.', 'Parks, gardens, museums, beaches and activities: plan an outing that suits everyone.', 'حدائق، متاحف، شواطئ وأنشطة: تحضير خرجة تناسب الجميع.'),
    steps: [
      'Choisissez une zone et le temps de trajet que vous souhaitez consacrer à la sortie.',
      'Précisez les âges, les envies, le budget et les besoins d’accessibilité de votre groupe.',
      'Vérifiez directement les horaires pour la date choisie, les conditions d’accès et la réservation éventuelle.',
      'Pour une activité en extérieur, consultez les conditions locales et les consignes du gestionnaire.',
      'Gardez une autre idée à proximité en cas de fermeture ou de changement de programme.',
    ],
  },
  {
    slug: 'restaurants',
    theme: 'decouvrir',
    approved: true,
    title: t('Restaurants, cafés et bonnes tables', 'Restaurants, cafés and good tables', 'مطاعم ومقاهٍ وموائد طيبة'),
    summary: t('Choisir une adresse selon le quartier, ses envies et les besoins de son groupe.', 'Choose a place by neighbourhood, taste and your group’s needs.', 'اختيار عنوان حسب الحي والرغبات واحتياجات المجموعة.'),
    steps: [
      'Définissez le quartier, le nombre de personnes, l’horaire et votre budget.',
      'Consultez un menu récent et confirmez directement les prix, l’ouverture et la réservation.',
      'Demandez les informations utiles : accueil des enfants, accès, terrasse ou possibilités pour votre groupe.',
      'Si vous avez une allergie ou une contrainte alimentaire, faites confirmer les ingrédients et les précautions par l’établissement.',
      'Lisez plusieurs retours récents en distinguant expériences personnelles et informations confirmées.',
    ],
  },
  {
    slug: 'pharmacies',
    theme: 'quotidien',
    approved: false,
    title: t('Trouver une pharmacie', 'Finding a pharmacy', 'إيجاد صيدلية'),
    summary: t('Repérer les pharmacies proches et les pharmacies de garde.', 'Locate nearby and on-duty pharmacies.', 'تحديد الصيدليات القريبة وصيدليات المناوبة.'),
    steps: [
      'Repérez les pharmacies proches de votre domicile et de votre lieu de travail.',
      'Renseignez-vous sur l’organisation des gardes de nuit et de week-end dans votre commune.',
      'Pour un traitement régulier, vérifiez la disponibilité du médicament avec votre pharmacien.',
      'Gardez vos ordonnances et la liste de vos traitements à portée de main.',
      'En cas d’urgence, contactez les services d’urgence plutôt que de chercher une pharmacie.',
    ],
  },
  {
    slug: 'services-au-quotidien',
    theme: 'quotidien',
    approved: false,
    title: t('Trouver le bon service au quotidien', 'Finding everyday services', 'إيجاد الخدمة المناسبة يوميًا'),
    summary: t('Artisans, commerces, réparations : identifier un prestataire fiable.', 'Tradespeople, shops, repairs: find a reliable provider.', 'حرفيون، متاجر، تصليحات: تحديد مقدّم خدمة موثوق.'),
    steps: [
      'Décrivez précisément votre besoin, le délai et le budget envisagé.',
      'Demandez plusieurs devis écrits et comparez-les sur les mêmes bases.',
      'Vérifiez les références, l’inscription et l’assurance du prestataire quand c’est pertinent.',
      'Fixez par écrit les délais, le prix et les modalités de paiement.',
      'Signalez au guide un prestataire fiable pour qu’il soit vérifié et partagé.',
    ],
  },
  {
    slug: 'mosquees-et-librairies',
    theme: 'quotidien',
    approved: false,
    title: t('Mosquées, enseignement coranique et librairies', 'Mosques, Quranic teaching and bookshops', 'المساجد والتعليم القرآني والمكتبات'),
    summary: t('Repérer les lieux de prière, les cours et les librairies près de chez soi.', 'Find prayer places, classes and bookshops near you.', 'تحديد أماكن الصلاة والدروس والمكتبات قرب منزلك.'),
    steps: [
      'Repérez les mosquées proches et leurs informations pratiques (espace femmes, accès).',
      'Pour un cours ou un enseignement, renseignez-vous directement sur le programme et l’encadrement.',
      'Demandez les horaires, les tranches d’âge et les conditions d’inscription.',
      'Pour les librairies, vérifiez les langues disponibles et les possibilités de commande.',
      'Proposez au guide une adresse utile pour qu’elle soit vérifiée.',
    ],
  },
  {
    slug: 'hajj-omra',
    theme: 'demarches',
    approved: false,
    title: t('Préparer un projet de Hajj ou d’Omra', 'Preparing for Hajj or Umrah', 'التحضير للحج أو العمرة'),
    summary: t('Vérifier les conditions, choisir un opérateur agréé et préparer son dossier.', 'Check requirements, choose an approved operator and prepare your file.', 'التحقق من الشروط، اختيار متعامل معتمد وتحضير الملف.'),
    steps: [
      'Consultez les conditions et le calendrier officiels auprès des autorités compétentes.',
      'Vérifiez l’agrément de l’agence auprès des organismes officiels avant tout paiement.',
      'Demandez un programme écrit : vols, hébergement, encadrement, prix et conditions d’annulation.',
      'Préparez les documents et rendez-vous médicaux demandés dans les délais.',
      'Conservez contrats, reçus et contacts de l’agence pendant tout le voyage.',
    ],
  },
]
