type T3 = { fr: string; en: string; ar: string }
export type SectorSeed = { slug: string; icon: string; title: T3; intro: T3; criteria: string[]; guide?: string; specialties: [string, T3][] }

const t = (fr: string, en: string, ar: string): T3 => ({ fr, en, ar })

export const SECTORS: SectorSeed[] = [
  {
    slug: 'restaurants-gastronomie',
    icon: 'utensils',
    title: t('Restaurants & Gastronomie', 'Restaurants & Food', 'المطاعم وفن الطبخ'),
    intro: t('Choisir une table, une pause gourmande ou un traiteur.', 'Choose a table, a sweet break or a caterer.', 'اختيار مائدة، استراحة شهية أو ممون حفلات.'),
    criteria: ['Adresse et horaires confirmés', 'Menu et fourchette de prix récents', 'Réservation et accueil des groupes', 'Accueil des enfants et accessibilité'],
    guide: 'restaurants',
    specialties: [
      ['restaurants', t('Restaurants', 'Restaurants', 'مطاعم')],
      ['cafes', t('Cafés', 'Cafés', 'مقاهي')],
      ['salons-de-the', t('Salons de thé', 'Tea rooms', 'صالونات الشاي')],
      ['patisseries', t('Pâtisseries', 'Pastry shops', 'محلات الحلويات')],
      ['glaciers', t('Glaciers', 'Ice-cream parlours', 'محلات المثلجات')],
      ['traiteurs', t('Traiteurs', 'Caterers', 'ممونو الحفلات')],
    ],
  },
  {
    slug: 'education-formation',
    icon: 'graduation',
    title: t('Éducation & Formation', 'Education & Training', 'التعليم والتكوين'),
    intro: t('Comparer les parcours, les programmes et les conditions de scolarité.', 'Compare curricula, programmes and enrolment conditions.', 'مقارنة المسارات والبرامج وشروط التمدرس.'),
    criteria: ['Agrément et statut de l’établissement', 'Niveaux, langues et programmes', 'Conditions et calendrier d’inscription', 'Frais de scolarité communiqués'],
    guide: 'ecole-et-famille',
    specialties: [
      ['creches', t('Crèches', 'Nurseries', 'دور الحضانة')],
      ['ecoles', t('Écoles', 'Schools', 'المدارس')],
      ['universites', t('Universités', 'Universities', 'الجامعات')],
      ['formation-professionnelle', t('Formation professionnelle', 'Vocational training', 'التكوين المهني')],
      ['ecoles-de-langues', t('Écoles de langues', 'Language schools', 'مدارس اللغات')],
      ['enseignement-coranique', t('Enseignement coranique', 'Quranic teaching', 'التعليم القرآني')],
    ],
  },
  {
    slug: 'sante-soins',
    icon: 'health',
    title: t('Santé & Soins', 'Health & Care', 'الصحة والعلاج'),
    intro: t('Identifier les structures de soins et les professionnels adaptés à son besoin.', 'Find the right care facilities and practitioners for your needs.', 'تحديد هياكل العلاج والمهنيين المناسبين لحاجتك.'),
    criteria: ['Autorisation d’exercice', 'Spécialités et prise de rendez-vous', 'Horaires et gardes', 'Langues parlées'],
    guide: 'sante',
    specialties: [
      ['medecins', t('Médecins', 'Doctors', 'الأطباء')],
      ['cliniques', t('Cliniques', 'Clinics', 'العيادات')],
      ['hopitaux', t('Hôpitaux', 'Hospitals', 'المستشفيات')],
      ['laboratoires', t('Laboratoires', 'Laboratories', 'المخابر')],
      ['pharmacies', t('Pharmacies', 'Pharmacies', 'الصيدليات')],
    ],
  },
  {
    slug: 'bien-etre-sport',
    icon: 'wellness',
    title: t('Bien-être & Sport', 'Wellness & Sport', 'الرفاهية والرياضة'),
    intro: t('Prendre soin de soi et trouver une activité régulière.', 'Look after yourself and find a regular activity.', 'الاعتناء بالنفس وإيجاد نشاط منتظم.'),
    criteria: ['Horaires et espaces femmes / hommes', 'Tarifs et formules', 'Encadrement et hygiène', 'Accessibilité'],
    specialties: [
      ['spas', t('Spas', 'Spas', 'المنتجعات الصحية')],
      ['hammams', t('Hammams', 'Hammams', 'الحمّامات')],
      ['soins-esthetiques', t('Soins esthétiques', 'Beauty care', 'العناية التجميلية')],
      ['salles-de-sport', t('Salles de sport', 'Gyms', 'قاعات الرياضة')],
      ['clubs-sportifs', t('Clubs sportifs', 'Sports clubs', 'النوادي الرياضية')],
      ['installations-sportives', t('Installations sportives', 'Sports facilities', 'المنشآت الرياضية')],
    ],
  },
  {
    slug: 'logement-immobilier',
    icon: 'home',
    title: t('Logement & Immobilier', 'Housing & Real estate', 'السكن والعقار'),
    intro: t('Trouver les interlocuteurs pour louer, acheter ou gérer un logement.', 'Find the right people to rent, buy or manage a home.', 'إيجاد المحاورين للكراء أو الشراء أو تسيير مسكن.'),
    criteria: ['Agrément de l’agence', 'Zones couvertes', 'Honoraires communiqués par écrit', 'Mandats et documents fournis'],
    guide: 'logement',
    specialties: [
      ['agences-immobilieres', t('Agences immobilières', 'Estate agencies', 'الوكالات العقارية')],
      ['programmes-immobiliers', t('Programmes immobiliers', 'New developments', 'المشاريع العقارية')],
      ['gestion-locative', t('Gestion locative', 'Property management', 'تسيير الإيجار')],
    ],
  },
  {
    slug: 'hebergement-sejours',
    icon: 'hotel',
    title: t('Hébergement & Séjours', 'Stays & Travel', 'الإيواء والإقامة'),
    intro: t('Préparer un séjour et identifier les opérateurs de voyage.', 'Plan a stay and find travel operators.', 'تحضير إقامة وتحديد متعاملي السفر.'),
    criteria: ['Classement ou agrément', 'Conditions de réservation et d’annulation', 'Services inclus', 'Accessibilité'],
    guide: 'hajj-omra',
    specialties: [
      ['hotels', t('Hôtels', 'Hotels', 'الفنادق')],
      ['residences', t('Résidences', 'Residences', 'الإقامات')],
      ['maisons-d-hotes', t('Maisons d’hôtes', 'Guest houses', 'دور الضيافة')],
      ['agences-de-voyages', t('Agences de voyages', 'Travel agencies', 'وكالات السفر')],
      ['omra', t('Omra', 'Umrah', 'العمرة')],
      ['hajj', t('Hajj', 'Hajj', 'الحج')],
    ],
  },
  {
    slug: 'culture-nature-loisirs',
    icon: 'trees',
    title: t('Culture, Nature & Loisirs', 'Culture, Nature & Leisure', 'الثقافة والطبيعة والترفيه'),
    intro: t('Des lieux pour apprendre, se promener et partager une sortie.', 'Places to learn, stroll and share an outing.', 'أماكن للتعلّم والتنزّه ومشاركة خرجة.'),
    criteria: ['Horaires et jours d’ouverture', 'Tarifs d’entrée', 'Conditions d’accès', 'Activités pour enfants'],
    guide: 'sorties-en-famille',
    specialties: [
      ['musees', t('Musées', 'Museums', 'المتاحف')],
      ['bibliotheques', t('Bibliothèques', 'Libraries', 'المكتبات')],
      ['parcs', t('Parcs', 'Parks', 'الحدائق العامة')],
      ['plages', t('Plages', 'Beaches', 'الشواطئ')],
      ['jardins', t('Jardins', 'Gardens', 'البساتين')],
      ['activites-familiales', t('Activités familiales', 'Family activities', 'أنشطة عائلية')],
    ],
  },
  {
    slug: 'mosquees-lieux-de-priere',
    icon: 'mosque',
    title: t('Mosquées & Lieux de prière', 'Mosques & Prayer spaces', 'المساجد وأماكن الصلاة'),
    intro: t('Repérer les lieux de prière et leurs informations pratiques.', 'Find places of prayer and their practical details.', 'تحديد أماكن الصلاة ومعلوماتها العملية.'),
    criteria: ['Adresse confirmée', 'Espace femmes', 'Prière du vendredi', 'Accessibilité'],
    guide: 'mosquees-et-librairies',
    specialties: [
      ['mosquees', t('Mosquées', 'Mosques', 'المساجد')],
      ['espaces-de-priere', t('Espaces de prière', 'Prayer spaces', 'المصليات')],
    ],
  },
  {
    slug: 'commerces-achats',
    icon: 'shop',
    title: t('Commerces & Achats', 'Shops & Shopping', 'المتاجر والتسوق'),
    intro: t('Trouver les commerces utiles près de chez soi.', 'Find useful shops near you.', 'إيجاد المتاجر المفيدة قرب منزلك.'),
    criteria: ['Adresse et horaires', 'Moyens de paiement', 'Livraison', 'Retours et garanties'],
    guide: 'services-au-quotidien',
    specialties: [
      ['librairies', t('Librairies', 'Bookshops', 'المكتبات التجارية')],
      ['alimentation', t('Alimentation', 'Groceries', 'المواد الغذائية')],
      ['habillement', t('Habillement', 'Clothing', 'الملابس')],
      ['equipement-de-la-maison', t('Équipement de la maison', 'Homeware', 'تجهيز المنزل')],
    ],
  },
  {
    slug: 'transports-mobilite',
    icon: 'bus',
    title: t('Transports & Mobilité', 'Transport & Mobility', 'النقل والتنقل'),
    intro: t('Organiser ses trajets et le transport de ses biens.', 'Organise your journeys and move your belongings.', 'تنظيم التنقلات ونقل الممتلكات.'),
    criteria: ['Agrément ou registre de commerce', 'Zones desservies', 'Tarifs et devis écrits', 'Assurance'],
    guide: 'transport',
    specialties: [
      ['transporteurs', t('Transporteurs', 'Carriers', 'الناقلون')],
      ['location-de-vehicules', t('Location de véhicules', 'Car rental', 'كراء السيارات')],
      ['demenagement', t('Déménagement', 'Removals', 'نقل الأثاث')],
      ['services-automobiles', t('Services automobiles', 'Car services', 'خدمات السيارات')],
    ],
  },
  {
    slug: 'maison-travaux',
    icon: 'hammer',
    title: t('Maison & Travaux', 'Home & Building work', 'المنزل والأشغال'),
    intro: t('Choisir les compétences pour construire, rénover et entretenir.', 'Choose the right skills to build, renovate and maintain.', 'اختيار الكفاءات للبناء والترميم والصيانة.'),
    criteria: ['Qualification et inscription', 'Références de chantiers', 'Devis écrits', 'Assurance et garanties'],
    specialties: [
      ['architectes', t('Architectes', 'Architects', 'المهندسون المعماريون')],
      ['artisans', t('Artisans', 'Craftspeople', 'الحرفيون')],
      ['construction', t('Construction', 'Construction', 'البناء')],
      ['renovation', t('Rénovation', 'Renovation', 'الترميم')],
      ['entretien', t('Entretien', 'Maintenance', 'الصيانة')],
    ],
  },
  {
    slug: 'droit-finance-conseil',
    icon: 'scale',
    title: t('Droit, Finance & Conseil', 'Law, Finance & Advice', 'القانون والمالية والاستشارة'),
    intro: t('Trouver le bon interlocuteur pour une question professionnelle ou personnelle.', 'Find the right adviser for a professional or personal matter.', 'إيجاد المحاور المناسب لمسألة مهنية أو شخصية.'),
    criteria: ['Inscription à l’ordre ou agrément', 'Domaines de compétence', 'Honoraires annoncés', 'Langues de travail'],
    guide: 'travail-et-entreprise',
    specialties: [
      ['avocats', t('Avocats', 'Lawyers', 'المحامون')],
      ['notaires', t('Notaires', 'Notaries', 'الموثقون')],
      ['comptables', t('Comptables', 'Accountants', 'المحاسبون')],
      ['banques', t('Banques', 'Banks', 'البنوك')],
      ['conseil-aux-entreprises', t('Conseil aux entreprises', 'Business advisory', 'استشارة المؤسسات')],
    ],
  },
  {
    slug: 'administrations-services-publics',
    icon: 'landmark',
    title: t('Administrations & Services publics', 'Public services', 'الإدارات والخدمات العمومية'),
    intro: t('Identifier le service compétent et les contacts utiles.', 'Identify the competent office and useful contacts.', 'تحديد المصلحة المختصة وجهات الاتصال المفيدة.'),
    criteria: ['Compétence territoriale', 'Adresse officielle', 'Horaires', 'Rendez-vous', 'Documents demandés', 'Accessibilité'],
    guide: 'documents-et-demarches',
    specialties: [
      ['administrations', t('Administrations', 'Administrations', 'الإدارات')],
      ['consulats', t('Consulats', 'Consulates', 'القنصليات')],
      ['services-municipaux', t('Services municipaux', 'Municipal services', 'المصالح البلدية')],
      ['contacts-utiles-et-urgences', t('Contacts utiles et urgences', 'Useful & emergency contacts', 'أرقام مفيدة وطوارئ')],
    ],
  },
]

/** Les 58 wilayas (découpage de 2019). Les nouvelles wilayas s’ajoutent dans l’admin. */
export const WILAYAS: [number, string, string][] = [
  [1, 'Adrar', 'أدرار'], [2, 'Chlef', 'الشلف'], [3, 'Laghouat', 'الأغواط'], [4, 'Oum El Bouaghi', 'أم البواقي'], [5, 'Batna', 'باتنة'],
  [6, 'Béjaïa', 'بجاية'], [7, 'Biskra', 'بسكرة'], [8, 'Béchar', 'بشار'], [9, 'Blida', 'البليدة'], [10, 'Bouira', 'البويرة'],
  [11, 'Tamanrasset', 'تمنراست'], [12, 'Tébessa', 'تبسة'], [13, 'Tlemcen', 'تلمسان'], [14, 'Tiaret', 'تيارت'], [15, 'Tizi Ouzou', 'تيزي وزو'],
  [16, 'Alger', 'الجزائر'], [17, 'Djelfa', 'الجلفة'], [18, 'Jijel', 'جيجل'], [19, 'Sétif', 'سطيف'], [20, 'Saïda', 'سعيدة'],
  [21, 'Skikda', 'سكيكدة'], [22, 'Sidi Bel Abbès', 'سيدي بلعباس'], [23, 'Annaba', 'عنابة'], [24, 'Guelma', 'قالمة'], [25, 'Constantine', 'قسنطينة'],
  [26, 'Médéa', 'المدية'], [27, 'Mostaganem', 'مستغانم'], [28, 'M’Sila', 'المسيلة'], [29, 'Mascara', 'معسكر'], [30, 'Ouargla', 'ورقلة'],
  [31, 'Oran', 'وهران'], [32, 'El Bayadh', 'البيض'], [33, 'Illizi', 'إليزي'], [34, 'Bordj Bou Arréridj', 'برج بوعريريج'], [35, 'Boumerdès', 'بومرداس'],
  [36, 'El Tarf', 'الطارف'], [37, 'Tindouf', 'تندوف'], [38, 'Tissemsilt', 'تيسمسيلت'], [39, 'El Oued', 'الوادي'], [40, 'Khenchela', 'خنشلة'],
  [41, 'Souk Ahras', 'سوق أهراس'], [42, 'Tipaza', 'تيبازة'], [43, 'Mila', 'ميلة'], [44, 'Aïn Defla', 'عين الدفلى'], [45, 'Naâma', 'النعامة'],
  [46, 'Aïn Témouchent', 'عين تموشنت'], [47, 'Ghardaïa', 'غرداية'], [48, 'Relizane', 'غليزان'], [49, 'Timimoun', 'تيميمون'], [50, 'Bordj Badji Mokhtar', 'برج باجي مختار'],
  [51, 'Ouled Djellal', 'أولاد جلال'], [52, 'Béni Abbès', 'بني عباس'], [53, 'In Salah', 'عين صالح'], [54, 'In Guezzam', 'عين قزام'], [55, 'Touggourt', 'تقرت'],
  [56, 'Djanet', 'جانت'], [57, 'El M’Ghair', 'المغير'], [58, 'El Meniaa', 'المنيعة'],
]

export const FEATURED_WILAYAS = [16, 31, 25, 23, 13, 6]
